spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dabengxiang/cloud-config.git
  application:
    name: config
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka








server:
  port: 6080
management:
  endpoints:
    web:
      exposure:
        include: '*'


